#config_version=5
mode:
  start_events: ball_started
  priority: 100

ball_saves:
  ball_save_ball_save:
    active_time: 8s
    hurry_up_time: 3s
    grace_period: 2s
    timer_start_events: sw_playfield_active
    auto_launch: true
    balls_to_save: 1
show_player:
  ball_save_ball_save_ball_save_timer_start:
    flash_color:
      key: ball_save
      speed: 2
      show_tokens:
        lights: l_shoot_again_1, l_shoot_again_2
        color: red
  ball_save_ball_save_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again_1, l_shoot_again_2
        color: red
  ball_save_ball_save_ball_save_disabled:
    ball_save: stop

sounds:
  main_theme:
    volume: 0.50
    priority: 100

sound_player:
  # Base mode sound effects
  sw_bumper_active: laser5

  sw_spinner_active: laser10
  
  sw_standup_active: laser_gun_2

  s_10_pt_active: laser12

  sw_sling_active: laser13
  
  sw_rollover_active: activate_1

  sw_drain_active: complain_1

  sw_drop_target_active: laser13

  sw_tilt_warning_active: warning_voice

  # drop target 
  mode_bottom_drop_complete_started:
    danger:
      volume: 0.25
      loops: 0
      fade_out: 0.0
  drop_target_bank_lower_bank_up:
    danger:
      action: stop

  mode_top_drop_complete_started:
    danger:
      volume: 0.25
      loops: 0
      fade_out: 0.0
  drop_target_bank_upper_bank_up:
    danger:
      action: stop

  mode_base_started:
    landing_voice: 
      volume: 1
      loops: 0

  ball_save_ball_save_ball_save_saving_ball:
    ball_saved_voice:
      volume: 1
      loops: 0
    

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: Bonus (bonus_multiplier)
        y: top
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_name: Greenscr
        color: green
        font_size: 30
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_name: Greenscr
        font_size: 100
        color: green
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_name: Greenscr
        color: green
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_name: Greenscr
        color: green
        font_size: 50

variable_player:
  # Lower playfield
  s_left_sling_active:
    score: 20 
  s_right_sling_active:
    score: 20 
    playfield_bonus: (50 * current_player.bonus_multiplier)
  s_left_drain_rollover_active:
    score: 100
    playfield_bonus: (100 * current_player.bonus_multiplier)
  s_right_drain_rollover_active:
    score: 100
    playfield_bonus: (100 * current_player.bonus_multiplier)
  s_left_lower_pf_rollover_active:
    score: 50
  s_right_lower_pf_rollover_active:
    score: 50
  s_lower_inner_lane_rollover_active:
    score: 50

  # Drop target Lower
  s_lower_drop_1_active:
    score: 500
  s_lower_drop_2_active:
    score: 500
  s_lower_drop_3_active:
    score: 500
  s_lower_drop_4_active:
    score: 500
  s_lower_drop_5_active:
    score: 500
  # Drop target Upper
  s_upper_drop_1_active:
    score: 500
  s_upper_drop_2_active:
    score: 500
  s_upper_drop_3_active:
    score: 500
  s_upper_drop_4_active:
    score: 500
  s_upper_drop_5_active:
    score: 500

  # Behind drops
  s_behind_drops_active:
    score: 100
    playfield_bonus: (50 * current_player.bonus_multiplier)

  # Bumpers
  s_left_bumper_active:
    score: 100
    left_bumper_hits: 1
    total_bumper_hits: 1
  s_right_bumper_active:
    score: 100
    right_bumper_hits: 1
    total_bumper_hits: 1

  # Spinners
  s_right_spinner_active:
    score: 100
    total_spinner_hits: 1
  s_left_spinner_active:
    score: 100
    total_spinner_hits: 1

  # Upper Playfield
  s_left_upper_rollover_active:
    score: 50
    playfield_bonus: (50 * current_player.bonus_multiplier)
  s_right_upper_rollover_active:
    score: 50
    playfield_bonus: (50 * current_player.bonus_multiplier)
  s_10_pt_active:
    score: 100
  s_lower_left_target_active:
    score: 200
  s_lower_middle_target_active:
    score: 200
  s_target_front_rollover_active:
    score: 500
    playfield_bonus: (500* current_player.bonus_multiplier)
  s_upper_left_target_active:
    score: 200
  s_upper_right_target_active:
    score: 200

  # Loop
  s_rollthru_rollover_active:
    score: 500

  # Bonus
  drop_target_bank_lower_bank_down:
    total_drop_complete: 1
    playfield_bonus: (500 * current_player.bonus_multiplier)
  drop_target_bank_upper_bank_down:
    total_drop_complete: 1
    playfield_bonus: (500 * current_player.bonus_multiplier)

  shot_bonus_standup_hit:
    playfield_bonus: (500 * current_player.bonus_multiplier)

  # If the bonus multiplier is one or two, then add one
  increase_multiplier{current_player.bonus_multiplier <= 2}
    bonus_multiplier: 1

  # If the bonus multiplier is already three, then add 3
  increase_multiplier{current_player.bonus_multiplier == 3}
    bonus_multiplier: 3

shot_profiles:
  base_standup_targets:
    states:
      - name: unlit
        show: "off"
      - name: lit_on
        show: "on"
  base_rollovers:
    states:
      - name: unlit
        show: "off"
      - name: lit_on
        show: "on"

shots:
  shot_upper_right_standup:
    switch: s_upper_right_target
    profile: base_standup_targets
    show_tokens:
      light: l_top_right_200
  shot_upper_left_standup:
    switch: s_upper_left_target
    profile: base_standup_targets
    show_tokens:
      light: l_top_left_200
  shot_lower_left_standup:
    switch: s_lower_left_target
    profile: base_standup_targets
    show_tokens:
      light: l_lower_left_200
  shot_lower_middle_standup:
    switch: s_lower_middle_target
    profile: base_standup_targets
    show_tokens:
      light: l_upper_left_200
  shot_bonus_standup:
    switch: s_target_front_rollover
    profile: base_standup_targets
    show_tokens:
      light: l_500_left_bonus
  shot_loop_rollover:
    switch: s_rollthru_rollover
    profile: base_rollovers
    show_tokens:
      light: l_bonus_rollover
  shot_left_upper_rollover:
    switch: s_left_upper_rollover
    profile: base_rollovers
    show_tokens:
      light: l_50_left_rollover
  shot_right_upper_rollover:
    switch: s_right_upper_rollover
    profile: base_rollovers
    show_tokens:
      light: l_50_right_rollover
  shot_left_lower_rollover:
    switch: s_left_lower_pf_rollover
    profile: base_rollovers
    show_tokens:
      light: l_bottom_left_rollover
  shot_right_lower_rollover:
    switch: s_right_lower_pf_rollover
    profile: base_rollovers
    show_tokens:
      light: l_bottom_right_rollover

accruals:
  bonus_multiplier:
    events:
      - shot_loop_rollover_hit
    events_when_complete: increase_multiplier, light_bonus_led
    start_enabled: true
