#config_version=5
mode:
  start_events: ball_started
  priority: 100

ball_saves:
  ball_save_ball_save:
    active_time: 10s
    hurry_up_time: 3s
    timer_start_events: balldevice_bd_drain_ejecting_ball
    auto_launch: true
    balls_to_save: 1

sounds:
  main_theme:
    volume: 0.75
    priority: 100

sound_player:
  mode_base_started:
    main_theme:
      loops: -1

  s_left_bumper_active: laser_5

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50

variable_player:
  # Lower playfield
  s_left_sling_active:
    score: 20 
  s_right_sling_active:
    score: 20 
  s_left_drain_rollover_active:
    score: 100
  s_right_drain_rollover_active:
    score: 100
  s_left_lower_pf_rollover_active:
    score: 50
  s_right_lower_pf_rollover_active:
    score: 50
  s_lower_inner_lane_rollover_active:
    score: 50

  # Drop target Lower
  s_lower_drop_1_active:
    score: 500
  s_lower_drop_2_active:
    score: 500
  s_lower_drop_3_active:
    score: 500
  s_lower_drop_4_active:
    score: 500
  s_lower_drop_5_active:
    score: 500
  # Drop target Upper
  s_upper_drop_1_active:
    score: 500
  s_upper_drop_2_active:
    score: 500
  s_upper_drop_3_active:
    score: 500
  s_upper_drop_4_active:
    score: 500
  s_upper_drop_5_active:
    score: 500

  # Behind drops
  s_behind_drops_active:
    score: 100

  # Bumpers
  s_left_bumper_active:
    score: 10
  s_right_bumper_active:
    score: 10

  # Spinners
  s_right_spinner_active:
    score: 10
  s_left_spinner_active:
    score: 10

  # Upper Playfield
  s_left_upper_rollover_active:
    score: 50
  s_right_upper_rollover_active:
    score: 50
  s_10_active:
    score: 10
  s_lower_left_target_active:
    score: 200
  s_lower_middle_target_active:
    score: 200
  s_target_front_rollover_active:
    score: 500
  s_upper_left_target_active:
    score: 200
  s_upper_right_target_active:
    score: 200

  # Loop
  s_rollthru_rollover_active:
    score: 100
