#config_version=5

# Base mode
# Author - Michael Latiolais

# Mode starts with a new ball
mode:
  start_events: ball_started
  priority: 100

# Set up initial ball save
ball_saves:
  bs_base:
    active_time: 8s
    hurry_up_time: 3s
    grace_period: 2s
    timer_start_events: sw_playfield_active, sw_bumper_active, sw_standup_active, sw_rollover_active
    auto_launch: true
    balls_to_save: 1

counters:
  # The counter used for the loops
  loop_complete_count:
    count_events: shot_loop_rollover_hit
    events_when_hit: loop_done
    starting_count: 0
    direction: up
    persist_state: false

shows:
  # Turn one of the bonus lamps on
  bonus_lamp_on:
    - time: 0
      lights:
        (led1): white

  # Turn both bonus lamps on
  bonus_both_lamps_on:
    - time: 0
      lights:
        (led1): white
        (led2): white

  # Turn both bonus lamps off
  bonus_lamps_off:
    - time: 0
      lights:
        (led1): off
        (led2): off

show_player:
  # Ball save lamp show
  ball_save_bs_base_timer_start:
    flash_color:
      key: ball_save
      speed: 2
      show_tokens:
        lights: l_shoot_again_1, l_shoot_again_2
        color: red
  ball_save_bs_base_hurry_up:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again_1, l_shoot_again_2
        color: red
  ball_save_bs_base_disabled:
    ball_save: stop

  # Bonus lamp system
  # First loop, light double bonus
  # This is based on the counter defined in this file
  loop_done{count==1}:
    bonus_lamp_on:
      show_tokens:
        led1: l_double_bonus
  # Second loop, turn off bonus lamps and light triple
  loop_done{count==2}:
    bonus_lamps_off:
      show_tokens:
        led1: l_double_bonus
        led2: l_triple_bonus
    bonus_lamp_on:
      show_tokens:
        led1: l_triple_bonus
  # Third loop, light both bonus lamps
  loop_done{count==3}:
    bonus_both_lamps_on:
      show_tokens:
        led1: l_double_bonus
        led2: l_triple_bonus
 
  # Ball start reset
  mode_base_started:
    # Turn off bonus lamps during the start of the ball
    bonus_lamps_off:
      show_tokens:
        led1: l_double_bonus
        led2: l_triple_bonus
      

light_player:
  # The center bonus lamps
  # As the playfield_bonus reaches each threshold number, a new lamp is lit, starting at 
  # 1000 points
  # These go away when the playfield_bonus is reset
  "{current_player.playfield_bonus >= 1000}":
    l_1000_center_bonus: red
  "{current_player.playfield_bonus >= 2000}":
    l_2000_center_bonus: red
  "{current_player.playfield_bonus >= 3000}":
    l_3000_center_bonus: red
  "{current_player.playfield_bonus >= 4000}":
    l_4000_center_bonus: red
  "{current_player.playfield_bonus >= 5000}":
    l_5000_center_bonus: red
  "{current_player.playfield_bonus >= 6000}":
    l_6000_center_bonus: red
  "{current_player.playfield_bonus >= 7000}":
    l_7000_center_bonus: red
  "{current_player.playfield_bonus >= 8000}":
    l_8000_center_bonus: red
  "{current_player.playfield_bonus >= 9000}":
    l_9000_center_bonus: red
  "{current_player.playfield_bonus >= 10000}":
    l_10000_center_bonus: red
  "{current_player.playfield_bonus >= 20000}":
    l_20000_center_bonus: red
  "{current_player.playfield_bonus >= 40000}":
    l_double_bonus_center: red

sounds:
  main_theme:
    volume: 0.50
    priority: 100

sound_player:
  # Base mode sound effects
  # Most are based on tags
  # Any bumper
  sw_bumper_active: laser5

  # Any spinner
  sw_spinner_active: laser10
  
  # Any standup
  sw_standup_active: laser_gun_2

  # Since the 10 pt switches are all wired together, we use the switch event and not a tag
  s_10_pt_active: laser12

  # Any sling
  sw_sling_active: laser13
  
  # Any rollover
  sw_rollover_active: activate_1

  # Any drain rollover
  sw_drain_active: complain_1

  # Any drop target hit
  sw_drop_target_active: laser13

  # First tilt warning
  sw_tilt_warning_active: warning_voice

  # drop target 
  #mode_bottom_drop_complete_started:
  #  danger:
  #    volume: 0.25
  #    loops: 0
  #    fade_out: 0.0
  #drop_target_bank_lower_bank_up:
  #  danger:
  #    action: stop

  #mode_top_drop_complete_started:
  #  danger:
  #    volume: 0.25
  #    loops: 0
  #    fade_out: 0.0
  #drop_target_bank_upper_bank_up:
  #  danger:
  #    action: stop

  # Initial voice over
  # TODO - change this to only run on ball 1
  mode_base_started:
    landing_voice: 
      volume: 1
      loops: 0

  # Ball save voice
  ball_save_bs_base_saving_ball:
    ball_saved_voice:
      volume: 1
      loops: 0
    

slide_player:
  # Main display
  # TODO - add gif for landing animation on first ball
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_name: Greenscr
        font_size: 100
        color: green
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_name: Greenscr
        color: green
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_name: Greenscr
        color: green
        font_size: 50


variable_player:
  # Lower playfield
  s_left_sling_active:
    score: (20 * current_player.pf_multiplier)
  s_right_sling_active:
    score: (20 * current_player.pf_multiplier)
    playfield_bonus: 50
  s_left_drain_rollover_active:
    score: 100
    playfield_bonus: 100
  s_right_drain_rollover_active:
    score: 100
    playfield_bonus: 100
  s_left_lower_pf_rollover_active:
    score: (50 * current_player.pf_multiplier)
  s_right_lower_pf_rollover_active:
    score: (50 * current_player.pf_multiplier)
  s_lower_inner_lane_rollover_active:
    score: (50 * current_player.pf_multiplier)

  # Drop target Lower
  s_lower_drop_1_active:
    score: (500 * current_player.pf_multiplier)
  s_lower_drop_2_active:
    score: (500 * current_player.pf_multiplier)
  s_lower_drop_3_active:
    score: (500 * current_player.pf_multiplier)
  s_lower_drop_4_active:
    score: (500 * current_player.pf_multiplier)
  s_lower_drop_5_active:
    score: (500 * current_player.pf_multiplier)
  # Drop target Upper
  s_upper_drop_1_active:
    score: (500 * current_player.pf_multiplier)
  s_upper_drop_2_active:
    score: (500 * current_player.pf_multiplier)
  s_upper_drop_3_active:
    score: (500 * current_player.pf_multiplier)
  s_upper_drop_4_active:
    score: (500 * current_player.pf_multiplier)
  s_upper_drop_5_active:
    score: (500 * current_player.pf_multiplier)

  # Behind drops
  s_behind_drops_active:
    score: (100 * current_player.pf_multiplier)
    playfield_bonus: 50

  # Bumpers
  s_left_bumper_active:
    score: (100 * current_player.pf_multiplier)
    left_bumper_hits: 1
    total_bumper_hits: 1
  s_right_bumper_active:
    score: (100 * current_player.pf_multiplier)
    right_bumper_hits: 1
    total_bumper_hits: 1

  # Spinners
  s_right_spinner_active:
    score: (100 * current_player.pf_multiplier)
    total_spinner_hits: 1
  s_left_spinner_active:
    score: (100 * current_player.pf_multiplier)
    total_spinner_hits: 1

  # Upper Playfield
  s_left_upper_rollover_active:
    score: (50 * current_player.pf_multiplier)
    playfield_bonus: 50
  s_right_upper_rollover_active:
    score: (50 * current_player.pf_multiplier)
    playfield_bonus: 50
  s_10_pt_active:
    score: (100 * current_player.pf_multiplier)
  s_lower_left_target_active:
    score: (200 * current_player.pf_multiplier)
  s_lower_middle_target_active:
    score: (200 * current_player.pf_multiplier)
  s_target_front_rollover_active:
    score: (500 * current_player.pf_multiplier)
    playfield_bonus: 500
  s_upper_left_target_active:
    score: (200 * current_player.pf_multiplier)
  s_upper_right_target_active:
    score: (200 * current_player.pf_multiplier)

  # Loop
  s_rollthru_rollover_active:
    score: 500

  # Bonus
  drop_target_bank_lower_bank_down:
    total_drop_complete: 1
    playfield_bonus: 500
  drop_target_bank_upper_bank_down:
    total_drop_complete: 1
    playfield_bonus: 500

  shot_bonus_standup_hit:
    playfield_bonus: 500

  # First loop, set the multiplier to 2x
  # This is based on the counter defined in this file
  loop_done{count==1}:
    pf_multiplier:
      int: 2
      action: set
  # Second loop, set it to 2x
  loop_done{count==2}:
    pf_multiplier:
      int: 3
      action: set
  # Third loop, set it to 6x
  loop_done{count==3}:
    pf_multiplier:
      int: 6
      action: set

  # Ball start reset
  mode_base_started:
    # Reset multiplier to 1
    pf_multiplier:
      int: 1
      action: set
    # Reset playfield_bonus to 0
    # TODO - Add a mechanism for holding a bonus
    playfield_bonus:
      int: 0
      action: set

  # Attack mode scoring
  ape_beast_complete:
    score: 10000
    action: set

  # Attack mode scoring
  lizard_beast_complete:
    score: 10000
    action: set


shot_profiles:
  base_standup_targets:
    states:
      - name: unlit
        show: "off"
      - name: lit_on
        show: "on"
  base_rollovers:
    states:
      - name: unlit
        show: "off"
      - name: lit_on
        show: "on"

shots:
  shot_upper_right_standup:
    switch: s_upper_right_target
    profile: base_standup_targets
    show_tokens:
      light: l_top_right_200
  shot_upper_left_standup:
    switch: s_upper_left_target
    profile: base_standup_targets
    show_tokens:
      light: l_top_left_200
  shot_lower_left_standup:
    switch: s_lower_left_target
    profile: base_standup_targets
    show_tokens:
      light: l_lower_left_200
  shot_lower_middle_standup:
    switch: s_lower_middle_target
    profile: base_standup_targets
    show_tokens:
      light: l_upper_left_200
  shot_bonus_standup:
    switch: s_target_front_rollover
    profile: base_standup_targets
    show_tokens:
      light: l_500_left_bonus
  shot_loop_rollover:
    switch: s_rollthru_rollover
    profile: base_rollovers
    show_tokens:
      light: l_bonus_rollover
    delay_switch:
      s_rollthru_rollover: 2s
  shot_left_upper_rollover:
    switch: s_left_upper_rollover
    profile: base_rollovers
    show_tokens:
      light: l_50_left_rollover
  shot_right_upper_rollover:
    switch: s_right_upper_rollover
    profile: base_rollovers
    show_tokens:
      light: l_50_right_rollover
  shot_left_lower_rollover:
    switch: s_left_lower_pf_rollover
    profile: base_rollovers
    show_tokens:
      light: l_bottom_left_rollover
  shot_right_lower_rollover:
    switch: s_right_lower_pf_rollover
    profile: base_rollovers
    show_tokens:
      light: l_bottom_right_rollover
