#config_version=5

# Lizard Beast attack mode
# Author - Michael Latiolais

# Starts with dropping the upper bank
# TODO - Add timer
# TODO - Add counter for spinner hits
mode:
  start_events: drop_target_bank_lower_bank_down
  stop_events: timer_lizard_attack_timer_complete, lizard_beast_complete
  priority: 200

variable_player:
  counter_lizard_beast_attack_hit:
    lizard_counter:
      action: set
      int: (count)
  mode_lizard_beast_started:
    lizard_counter:
      action: set
      int: (15 * (current_player.lizard_beast_mode_count + 1))


sound_player:
  mode_lizard_beast_started:
    attack_is_imminent_voice:
      volume: 1
      loops: 0

counters:
  lizard_beast_attack:
    count_events: sw_bumper_active
    starting_count: (15 * (current_player.lizard_beast_mode_count + 1))
    count_complete_value: 0
    direction: down
    events_when_complete: lizard_beast_complete

timers:
    lizard_attack_timer:
        debug: True
        start_value: 30
        end_value: 0
        direction: down
        tick_interval: 1s
        control_events:
          - action: start
            event: mode_lizard_beast_started
          - action: stop 
            event: lizard_beast_complete

slide_player:
  mode_lizard_beast_started:
    widgets:
      - type: text
        text: Pop Hits Remaining (lizard_counter)
        number_grouping: true
        min_digits: 2
        font_name: Greenscr
        font_size: 30
        color: red


