#config_version=5
mode:
  start_events: drop_target_bank_lower_bank_down
  stop_events: drop_target_bank_lower_bank_up
  priority: 500

variable_player:
  s_behind_drops_active:
    score: 2000

sound_player:
  mode_bottom_drop_complete_started:
    danger:
      volume: 0.25
      loops: 0
  mode_bottom_drop_complete_stopped:
    danger:
      action: stop

