#config_version=5

coils:

  # Coils
  c_flipper_right:
    number: 0-0-1
    allow_enable: true
    default_hold_power: 1.0
    default_pulse_ms: 50
  c_flipper_left:
    number: 0-0-2
    allow_enable: true
    default_hold_power: 1.0
    default_pulse_ms: 50
  c_left_slingshot:
    number: 0-0-3
    allow_enable: true
    default_hold_power: 1.0
  c_right_slingshot:
    number: 0-0-4
    allow_enable: true
    default_hold_power: 1.0
  c_plunger_lane:
    number: 0-0-5
    label:
    tags:
    default_pulse_ms: 25

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_sling
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_sling
