#config_version=5

coils:

  # Coils
  c_flipper_right:
    number: 1-0-1
    allow_enable: true
    default_hold_power: 1.0
    default_pulse_ms: 50
  c_flipper_left:
    number: 1-0-7
    allow_enable: true
    default_hold_power: 1.0
    default_pulse_ms: 50
  c_left_slingshot:
    number: 0-0-10
    default_pulse_ms: 15
  c_right_slingshot:
    number: 0-0-0
    default_pulse_ms: 15
  c_plunger_lane:
    number: 1-0-4
    label:
    tags:
    default_pulse_ms: 25

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_sling
    enable_events: machine_reset_phase_3
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_sling
    enable_events: machine_reset_phase_3
