#config_version=5

coils:

  # Coils
  # Main cobrapin - Bank B
  c_right_slingshot:
    number: 0-0-1
    default_pulse_ms: 40
  c_left_slingshot:
    number: 0-0-2
    default_pulse_ms: 40
  c_left_bumper:
    number: 0-0-6
    default_pulse_ms: 40

  # Main cobrapin - Bank C
  c_right_bumper:
    number: 1-0-1
    default_pulse_ms: 40
  c_right_drop_reset:
    number: 1-0-2
    default_pulse_ms: 50
  c_left_drop_reset:
    number: 1-0-3
    default_pulse_ms: 50
  c_ball_eject:
    number: 0-0-7
    label:
    tags:
    default_pulse_ms: 50

  # Satellite Board
  c_flipper_right:
    number: 3-0-1
    allow_enable: true
    default_hold_power: 0.90
    default_pulse_ms: 50
  c_flipper_left:
    number: 3-0-2
    allow_enable: true
    default_hold_power: 0.90
    default_pulse_ms: 50
  c_knocker:
    number: 3-0-3

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_sling
    #enable_events: machine_reset_phase_3
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_sling
    #enable_events: machine_reset_phase_3
  left_bumper:
    coil: c_left_bumper
    switch: s_left_bumper
    #enable_events: machine_reset_phase_3
  right_bumper:
    coil: c_right_bumper
    switch: s_right_bumper
    #enable_events: machine_reset_phase_3
