#config_version=5

coils:

  # Coils
  c_flipper_right:
    number: 0-0-1
    allow_enable: true
    default_hold_power: 1.0
    default_pulse_ms: 50
  c_flipper_left:
    number: 0-0-1
    allow_enable: true
    default_hold_power: 1.0
    default_pulse_ms: 50
