#config_version=5

# Middle Earth Cobrapin Config
# Primary programmer: Michael Latiolais

# This section defines the type of hardware used to control the game.
# In this case, since we are using a cobrapin, it is opp, gen2
hardware:
  platform: opp
  driverboards: gen2


opp:
  #Use the USB ports defined by your OS for the two STM32 boards
  ports: /dev/ttyACM0, /dev/ttyACM1, /dev/ttyACM2

psus:
  default:
    # Gives the capacitors extra time to recharge after firing a coil
    # and eases the load on the power supply. Doesn't affect autofire
    # devices like flippers, pops, slings.
    release_wait_ms: 50   


# One giant config file can get difficult to manage. You can put any of 
# these config sections in its own yaml file and link to it with the 
# config section here      
config:
  - switches_config.yaml
  - coils_config.yaml
  - lamps_config.yaml
  - device_config.yaml

# This section defines the elements of the machine
machine:
  balls_installed: 1 # How many balls are physically in your game
  min_balls: 1 # How few balls can be accounted for before you can start a game

# This section defines some of the basics of the game
game:
  balls_per_game: 3
  max_players: 4

# MPF works primarily through modes. Each mode is defined in a separate directory under the modes directory
modes:
  #Add all your mode names here
  - attract
  - base
  - service
  - high_score
  - bonus
  - tilt
  #- match
  - lizard_beast
  - ape_beast

# This section is not used at this point
keyboard:   #use to drive your game from the computer for testing
  s:
    switch: s_start_button
  w:
    switch: s_10_pt
  o:
    switch: s_outhole_kicker
  l:
    switch: s_left_flipper
  r:
    switch: s_right_flipper
  #"/":
  #  switch: s_right_eos

# This section holds variables that are used to store values specific to a player
player_vars:
  # Total number of all bumper hits
  total_bumper_hits:
    initial_value: 0
    value_type: int
  # Total number of all spinner hits
  total_spinner_hits:
    initial_value: 0
    value_type: int
  # Total number of drop target completions
  total_drop_complete:
    initial_value: 0
    value_type: int
 
  # Playfield bonus and multiplier
  playfield_bonus:
    initial_value: 0
    value_type: int
  pf_multiplier:
    initial_value: 1
    value_type: int

  # Mode count variables
  total_mode_complete:
    initial_value: 0
    value_type: int
  ape_beast_mode_count:
    initial_value: 0
    value_type: int
  lizard_beast_mode_count:
    initial_value: 0
    value_type: int
  ape_counter:
    initial_value: 0
    value_type: int
  lizard_counter:
    initial_value: 0
    value_type: int

# This defines the properties of the apron display
displays:
  window:
    width: 800
    height: 600

# This defines the sound system
sound_system:
  tracks:
    voice:
      volume: 1
      priority: 2
      simultaneous_sounds: 1
      preload: true
    sfx:
      volume: 1
      priority: 1
      preload: true
      simultaneous_sounds: 7
    music:
      volume: 0.5
      simultaneous_sounds: 1

# This is also part of the sound system 
assets:
  sounds:
    default:
      load: on_demand
    music:
      track: music
    sfx:
      track: sfx
    voice:
      track: voice

# This is the sound player that sets up the initial music
sound_player:
  mode_base_started:
    main_theme:
      loops: -1
      start_at: 21.40

  # If the mode is stopped, stop the music
  mode_base_stopped:
    main_theme:
      action: stop

# Properties of widgets used in every mode
# in your machine wide config file
widget_styles:
  attract_mode_high_score_display_label:
    font_size: 30
    anchor_x: right
    anchor_y: top
    x: center-10
    bold: true
  attract_mode_high_score_display_name:
    font_size: 30
    anchor_x: right
    anchor_y: top
    x: center+70
  attract_mode_high_score_display_score:
    font_size: 30
    anchor_x: left
    anchor_y: top
    x: center+90
    number_grouping: true
    min_digits: 1
  text_small:
    font_size: 20
    color: white
  text_default:
    font_size: 30
    color: white
  text_large:
    font_size: 70
    color: white
  medium:
    font_name: pixelmix
    font_size: 40           # for LCDs you need to increase this to 30-40. also change the font above
    color: white
    adjust_top: 1
    adjust_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 30           # for LCDs you need to increase this to 30-40. also change the font above
    color: white
    adjust_top: 2
    adjust_bottom: 3

# When certain events happen, we want to disable and enable solenoids.
event_player:
  ball_starting:
    - cmd_flippers_enable
    - cmd_autofire_coils_enable
    - cmd_drop_targets_reset
  ball_ending:
    - cmd_flippers_disable
    - cmd_autofire_coils_disable
  tilt:
    - cmd_flippers_disable
    - cmd_autofire_coils_disable
  slam_tilt:
    - cmd_flippers_disable
    - cmd_autofire_coils_disable
