switches:

  #DIRECT SWITCHES
  #switch numbers are labelled in silkscreen on the board
  #s_left_flipper:
  #  number: 0-0-27
  #  tags: left_flipper
  #s_right_flipper:
  #  number: 0-0-26
  #  tags: right_flipper
  #s_startButton:
  #  number: 0-0-25
  #  tags: start
  s_outhole_kicker:
    number: 0-0-1
  s_right_sling:
    number: 0-0-2
    tags: sling
  s_left_sling:
    number: 0-0-3
    tags: sling
  s_left_drain_rollover:
    number: 0-0-8
  s_left_lower_pf_rollover:
    number: 0-0-9
  s_right_lower_pf_rollover:
    number: 0-0-10
  s_lower_inner_lane_rollover:
    number: 0-0-11
