#config_version=5

switches:

  #DIRECT SWITCHES
  #switch numbers are labelled in silkscreen on the board

  # Satellite board
  # Cabinet Switches
  s_left_flipper:
    number: 3-0-16
    tags: left_flipper
  s_right_flipper:
    number: 3-0-17
    tags: right_flipper
  s_start_button:
    number: 3-0-10
    tags: start
  s_test:
    number: 3-0-1
  s_volume_down:
    number: 3-0-2
  s_volume_up:
    number: 3-0-3
  s_coin:
    number: 3-0-11
  s_tilt_cab:
    number: 3-0-8
  s_tilt_bob:
    number: 3-0-9
  
  # Main cobrapin board
  # Playfield switches
  # Bank
  s_outhole_kicker:
    number: 0-0-17
  s_right_sling:
    number: 0-0-18
    tags: sling
  s_left_sling:
    number: 0-0-19
    tags: sling
  s_left_drain_rollover:
    number: 0-0-8
  s_left_lower_pf_rollover:
    number: 0-0-9
  s_right_lower_pf_rollover:
    number: 0-0-10
  s_lower_inner_lane_rollover:
    number: 0-0-11

  # Bank
  s_lower_drop_1:
    number: 
