#config_version=5

# Ape Beast attack mode
# Author - Michael Latiolais

# Starts with dropping the upper bank
mode:
  start_events: drop_target_bank_upper_bank_down
  stop_events: ape_beast_timeout, ape_beast_complete
  priority: 200

variable_player:
  logicblock_ape_beast_attack_updated:
    ape_beast_attack_count:
      action: set
      int: value

sound_player:
  mode_ape_beast_started:
    attack_is_imminent_voice:
      volume: 1
      loops: 0

counters:
  ape_beast_attack:
    count_events: sw_spinner_active
    events_when_hit: ape_attacked
    starting_count: (20 * (current_player.ape_beast_mode_count + 1))
    count_complete_value: 0
    direction: down
    events_when_complete: ape_beast_complete

timers:
    ape_attack_timer:
        debug: True
        start_value: (10 + (current_player.ape_beast_mode_count * 10))
        end_value: 0
        direction: down
        tick_interval: 1s
        start_running: yes
        control_events:
          - action: start
            event: mode_ape_beast_started
          - action: stop 
            event: ape_beast_timeout

slide_player:
  mode_ape_beast_started:
    widgets:
      - type: text
        text: Spinner Hits Remaining (player|ape_beast_attack_counter)
        number_grouping: true
        min_digits: 2
        font_name: Greenscr
        font_size: 30
        color: red


