#config_version=5
mode:
  start_events: drop_target_bank_upper_bank_down
  stop_events: drop_target_bank_upper_bank_up
  priority: 200

variable_player:

sounds:
  demo_man_main_theme:
    volume: 0.50
    priority: 100



