#config_version=5
queue_relay_player:
  match_no_match:
    post: no_match
    wait_for: slide_no_match_slide_removed
    pass_args: true
  match_has_match:
    post: has_match
    wait_for: slide_match_slide_removed
    pass_args: true
mode_settings:
  non_match_number_step: 10
slide_player:
  no_match:
    no_match_slide:
      expire: 3s
  has_match:
    match_slide:
      expire: 3s
sound_player:
  match_no_match:
    no_match_sound:
      action: play
  match_has_match:
    match_sound:
      action: play
slides:
  match_slide:
    - type: text
      text: MATCH
    - type: text
      text: "Player 1: (match_number0)"
      anchor_x: center
      anchor_y: center
      x: 0
      y: top-50
    - type: text
      text: "Player 2: (match_number1)"
      anchor_x: center
      anchor_y: center
      x: right
      y: top-50
    - type: text
      text: "Player 3: (match_number2)"
      anchor_x: center
      anchor_y: center
      x: 0
      y: bottom+50
    - type: text
      text: "Player 4: (match_number3)"
      anchor_x: center
      anchor_y: center
      x: right
      y: bottom+50
    - type: text
      text: "Match number: (winner_number)"
      anchor_x: center
      anchor_y: center
      x: center
      y: center
  no_match_slide:
    - type: text
      text: NO MATCH
      font_size: 12
      anchor_y: bottom
    - type: text
      text: "Player 1: (match_number0)"
    - type: text
      text: "Player 2: (match_number1)"
    - type: text
      text: "Player 3: (match_number2)"
    - type: text
      text: "Player 4: (match_number3)"
    - type: text
      text: "Match number: (winner_number)"
